---
env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  $: false
  PIXI: false
  TWEEN: false
  Popper: false
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
rules:
  object-curly-newline:
    - error
    - ObjectExpression:
        multiline: true
      ObjectPattern:
        multiline: true
      ImportDeclaration:
        multiline: true
      ExportDeclaration:
        multiline: true
  no-param-reassign:
    - error
    - props: false
  eol-last:
    - error
    - always
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  prefer-destructuring:
    - error
    - VariableDeclarator:
        array: false
        object: true
      AssignmentExpression:
        array: false
        object: true
    - enforceForRenamedProperties: false
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
